# Generated by Django 5.1.8 on 2025-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_contrato_contrato_assinado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_e_desempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1_bimestre', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota do 1° Bimestre')),
                ('nota_2_bimestre', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota do 2° Bimestre')),
                ('nota_3_bimestre', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota do 3° Bimestre')),
                ('nota_4_bimestre', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota do 4° Bimestre')),
            ],
        ),
    ]
