# Generated by Django 5.1.8 on 2025-05-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_alter_nota_e_desempenho_nota_1_bimestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_e_desempenho',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_nota', to='escola.aluno'),
        ),
    ]
