# Generated by Django 5.1.8 on 2025-04-09 14:44

import django.db.models.deletion
import escola.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_nome', models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciências da Natureza'), ('JG', 'Jogos'), ('MAT', 'Matemática'), ('PORT', 'Português'), ('EF', 'Educação Física'), ('HIST', 'História'), ('GEO', 'Geografia'), ('ART', 'Artes'), ('FILO', 'Filosofia'), ('SOCI', 'Sociologia'), ('ING', 'Inglês'), ('ESP', 'Espanhol')], max_length=50, verbose_name='Selecione o itinerário')),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome_aluno',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='sobrenome_aluno',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='class_choices',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nome_professor',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='sobrenome_professor',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='nome_responsavel',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='sobrenome_responsavel',
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_completo_aluno',
            field=models.CharField(max_length=200, null=True, verbose_name='Digite o nome do aluno completo'),
        ),
        migrations.AddField(
            model_name='professor',
            name='nome_completo_professor',
            field=models.CharField(max_length=200, null=True, verbose_name='Digite seu nome completo'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='nome_completo_responsavel',
            field=models.CharField(max_length=200, null=True, verbose_name='Digite o nome do responsável completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_telefone_aluno',
            field=models.CharField(max_length=15, validators=[escola.validate.telefone_validate], verbose_name='Digite o número do celular (xx) xxxxx-xxxx'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='numero_telefone_professor',
            field=models.CharField(max_length=15, validators=[escola.validate.telefone_validate], verbose_name='Digite o número do celular (xx) xxxxx-xxxx'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='numero_telefone_responsavel',
            field=models.CharField(max_length=15, validators=[escola.validate.telefone_validate], verbose_name='Digite o número do celular (xx) xxxxx-xxxx'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_nome',
            field=models.CharField(choices=[('1°', '1° Ano'), ('2°', '2° Ano'), ('3°', '3° Ano')], max_length=50, verbose_name='Selecione a turma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='subject_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='escola.materia'),
        ),
    ]
