# Generated by Django 5.1.8 on 2025-04-23 11:41

import django.db.models.deletion
import escola.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_materia_remove_aluno_nome_aluno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='adress',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep_aluno',
            field=models.CharField(max_length=100, null=True, validators=[escola.validate.cep_validate], verbose_name='Informe o Cep do responsavel'),
        ),
        migrations.AddField(
            model_name='professor',
            name='cep_professor',
            field=models.CharField(max_length=100, null=True, validators=[escola.validate.cep_validate], verbose_name='Informe o Cep do responsavel'),
        ),
        migrations.AddField(
            model_name='professor',
            name='class_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padrinho', to='escola.turma'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno_responsavel', to='escola.aluno'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='cep_responsavel',
            field=models.CharField(max_length=100, null=True, validators=[escola.validate.cep_validate], verbose_name='Informe o Cep do responsavel'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='CPF_aluno',
            field=models.CharField(max_length=11, null=True, validators=[escola.validate.cpf_validate], verbose_name='Informe o CPF do responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='class_choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turma_aluno', to='escola.turma'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='CPF_professor',
            field=models.CharField(max_length=11, null=True, validators=[escola.validate.cpf_validate], verbose_name='Informe o CPF do responsável'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='CPF_responsavel',
            field=models.CharField(max_length=11, null=True, validators=[escola.validate.cpf_validate], verbose_name='Informe o CPF do responsável'),
        ),
    ]
