# Generated by Django 5.1.8 on 2025-04-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_aluno_adress_remove_professor_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome_completo_aluno',
            new_name='nome_aluno',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='nome_completo_professor',
            new_name='nome_professor',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='nome_completo_responsavel',
            new_name='nome_responsavel',
        ),
    ]
