# Generated by Django 5.1.8 on 2025-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='contrato_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
