# Generated by Django 5.1.8 on 2025-06-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_nota_e_desempenho_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_e_desempenho',
            name='boletim_pdf',
            field=models.FileField(blank=True, null=True, upload_to='boletins/'),
        ),
    ]
