# Generated by Django 5.1.8 on 2025-06-11 12:37

import escola.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0013_add_materia_to_nota_e_desempenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='senha_de_acesso',
            field=models.CharField(max_length=5, null=True, validators=[escola.validate.senha_validate], verbose_name='Digite a senha de acesso do professor. (5 dígitos)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='CPF_aluno',
            field=models.CharField(max_length=11, null=True, validators=[escola.validate.cpf_validate], verbose_name='Informe o CPF do aluno.'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cep_aluno',
            field=models.CharField(max_length=100, null=True, validators=[escola.validate.cep_validate], verbose_name='Informe o Cep. (Formato xxxxx-xxx)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento_aluno',
            field=models.DateField(max_length=10, verbose_name='Digite a data de nascimento do aluno. (Formato xxxxx-xxx)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email_aluno',
            field=models.EmailField(max_length=100, verbose_name='Digite o e-mail do aluno.'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(max_length=200, null=True, verbose_name='Digite o nome do aluno completo.'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_matricula_aluno',
            field=models.CharField(max_length=6, verbose_name='Digite o número da matricula do aluno. (5 dígitos)'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero_telefone_aluno',
            field=models.CharField(max_length=15, validators=[escola.validate.telefone_validate], verbose_name='Digite o número do celular do aluno. (Formato: 629xxxxxxxx)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='CPF_professor',
            field=models.CharField(max_length=11, null=True, validators=[escola.validate.cpf_validate], verbose_name='Informe o CPF do professor.'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cep_professor',
            field=models.CharField(max_length=100, null=True, validators=[escola.validate.cep_validate], verbose_name='Informe o Cep do professor. (Formato xxxxx-xxx)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='data_nascimento_professor',
            field=models.DateField(max_length=10, verbose_name='Digite a data de nascimento do professor. (Formato aaaa-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_professor',
            field=models.CharField(max_length=200, null=True, verbose_name='Digite o nome completo do professor.'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='numero_matricula_professor',
            field=models.CharField(max_length=6, verbose_name='Digite o número da matricula do professor. (5 dígitos)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='numero_telefone_professor',
            field=models.CharField(max_length=15, validators=[escola.validate.telefone_validate], verbose_name='Digite o número do celular do professor. (Formato: 629xxxxxxxx)'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='CPF_responsavel',
            field=models.CharField(max_length=11, null=True, validators=[escola.validate.cpf_validate], verbose_name='Informe o CPF do responsável.'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cep_responsavel',
            field=models.CharField(max_length=100, null=True, validators=[escola.validate.cep_validate], verbose_name='Informe o Cep. (Formato xxxxx-xxx)'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='data_nascimento_responsavel',
            field=models.DateField(max_length=10, verbose_name='Digite a data de nascimento do responsável. (Formato aaaa-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='email_responsavel',
            field=models.EmailField(max_length=100, verbose_name='Digite o e-mail do responsável.'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='nome_responsavel',
            field=models.CharField(max_length=200, null=True, verbose_name='Digite o nome do responsável completo.'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='numero_telefone_responsavel',
            field=models.CharField(max_length=15, validators=[escola.validate.telefone_validate], verbose_name='Digite o número do celular do responsável. (Formato: 629xxxxxxxx)'),
        ),
    ]
