# Generated by Django 5.1.8 on 2025-06-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0014_professor_senha_de_acesso_alter_aluno_cpf_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_e_desempenho',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_professor', to='escola.professor'),
        ),
    ]
