# Generated by Django 5.1.8 on 2025-06-11 13:56

import escola.validate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0015_nota_e_desempenho_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_e_desempenho',
            name='senha_de_acesso_professor',
            field=models.CharField(max_length=5, null=True, validators=[escola.validate.senha_validate], verbose_name='Digite a senha de acesso do professor. (5 dígitos)'),
        ),
    ]
